name: Electron Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - main

jobs:
  macos_build:
    name: MacOS
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: |
          npm ci
          ls -al node_modules/electron/dist/
          npm run fetch
          npm run icon

      - name: Build
        if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
        run: npm run make

      - name: Publish Release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  linux_build:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: |
          sudo apt-get install -y xvfb
          npm ci
          xvfb-run npm run fetch
          npm run icon

      - name: Build
        if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
        run: npm run make

      - name: Publish Release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  windows_build:
    name: Windows
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Build
        if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
        run: npm run make

      - name: Publish Release
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
