name: Electron Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - main

jobs:
  macos_build:
    name: macOS
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Check for GitHub Labels
        id: seekingTesters
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [[ -n "$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s "${{ github.event.pull_request.url }}" | jq -e '.labels[] | select(.name == "Seeking Testers")')" ]] {
            print 'found=true' >> $GITHUB_OUTPUT
          } else {
            print 'found=false' >> $GITHUB_OUTPUT
          }

      - name: Build
        if: ${{ success() && (github.event_name == 'pull_request' || steps.seekingTesters.outputs.found == 'false') }}
        run: npm run make

      - name: Publish Release
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        run: npm run publish

  linux_build:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Check for GitHub Labels
        id: seekingTesters
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          if [[ -n "$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -s "${{ github.event.pull_request.url }}" | jq -e '.labels[] | select(.name == "Seeking Testers")')" ]]; then
            echo 'found=true' >> $GITHUB_OUTPUT
          else
            echo 'found=false' >> $GITHUB_OUTPUT
          fi

      - name: Build
        if: ${{ success() && (github.event_name == 'pull_request' || steps.seekingTesters.outputs.found == 'false') }}
        run: npm run make

      - name: Publish Release
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        run: npm run publish

  windows_build:
    name: Window
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Check for GitHub Labels
        id: seekingTesters
        working-directory: ${{ github.workspace }}/plugin
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          ## GITHUB LABEL SCRIPT
          $LabelFound = try {
            $Params = @{
              Authentication = 'Bearer'
              Token = (ConvertTo-SecureString '${{ secrets.GITHUB_TOKEN }}' -AsPlainText)
              Uri = '${{ github.event.pull_request.url }}'
              UseBasicParsing = $true
            }

            (Invoke-RestMethod @Params).labels.name.contains('Seeking Testers')
          } catch {
            $false
          }

          "found=$(([string]${LabelFound}).ToLower())" >> $env:GITHUB_OUTPUT

      - name: Build
        if: ${{ success() && (github.event_name == 'pull_request' || steps.seekingTesters.outputs.found != 'true') }}
        run: npm run make

      - name: Publish Release
        if: ${{ success() && (github.event_name != 'pull_request' || steps.seekingTesters.outputs.found == 'true') }}
        run: npm run publish
